import { html } from "hono/html";
import type { CgiContext } from ".";

export const generateCgiInfo = ({
	$_SERVER,
	$_SESSION,
	$_REQUEST,
	config,
}: Pick<CgiContext, "$_SERVER" | "$_SESSION" | "$_REQUEST" | "config">) => {
	return () => {
		const infoSection = ({ title, data }: { title: string; data: any }) => {
			return html`
			<div style="margin-bottom: 20px; width: 100%; max-width: 900px;">
				<h2 style="background: #ccccff; color: #000; padding: 5px 10px; margin: 0; font-size: 1.2em; border: 1px solid #000; font-family: 'MS PGothic', sans-serif;">${title}</h2>
				<table style="width: 100%; border-collapse: collapse; border: 1px solid #000; table-layout: fixed; font-family: 'MS PGothic', sans-serif;">
					${Object.entries(data).map(
						([key, val], i) => html`
						<tr style="background: ${i % 2 === 0 ? "#f0f0ff" : "#ffffff"}">
							<td style="padding: 3px 10px; border: 1px solid #000; font-weight: bold; width: 30%; word-break: break-all;">${key}</td>
							<td style="padding: 3px 10px; border: 1px solid #000; width: 70%; word-break: break-all;">
								${typeof val === "object" ? JSON.stringify(val, null, 2) : String(val)}
							</td>
						</tr>
					`,
					)}
				</table>
			</div>
			`;
		};

		return html`
		<div style="background: #ffffff; color: #333333; font-family: 'MS PGothic', sans-serif; padding: 20px; display: flex; flex-direction: column; align-items: center;">
			<h1 style="color: #000000; border-bottom: 3px double #000000; padding-bottom: 10px; margin-bottom: 30px;">Matchbox CGI Version Information</h1>
			<div style="width: 100%; max-width: 900px; padding: 15px; background: #ffffcc; border: 1px dashed #000000; margin-bottom: 20px; text-align: center;">
				<strong>Server Software:</strong> Matchbox Engine on ${typeof process !== "undefined" ? "Node.js/Bun" : "Edge"}
			</div>
			${infoSection({ title: "$_SERVER (Environment)", data: $_SERVER })}
			${infoSection({ title: "$_SESSION", data: $_SESSION })}
			${infoSection({ title: "$_REQUEST", data: $_REQUEST })}
			${infoSection({ title: "Site Configuration", data: config })}
			<div style="margin-top: 40px; font-size: 0.9em; font-style: italic; border-top: 1px solid #ccc; width: 100%; max-width: 900px; text-align: right; padding-top: 10px;">
				Generated by Matchbox Framework - Ignition for Hono
			</div>
		</div>
		`;
	};
};

export const generateCgiError = ({
	error,
	$_SERVER,
}: {
	error: any;
	$_SERVER: CgiContext["$_SERVER"];
}) => {
	return html`
		 <div style="padding:2rem; background:#fffafa; border:5px double #cc0000; font-family: 'MS PGothic', sans-serif;">
				<h1 style="color:#cc0000; border-bottom: 2px solid #cc0000; padding-bottom: 5px;">Matchbox: Runtime Exception</h1>
				<p><strong>Fatal Error:</strong> ${error.message}</p>
				<pre style="background:#f0f0f0; padding:1rem; border:1px inset #ccc; overflow: auto;">${error.stack}</pre>
				<hr style="border: 0; border-top: 1px solid #cc0000;" />
				<div style="text-align: right; font-size: 0.8em;">Matchbox CGI Engine Server at ${$_SERVER.REMOTE_ADDR}</div>
			</div>
	`;
};
