name: release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: voidzero-dev/setup-vp@v1.20.0
        with:
          node-version-file: .node-version
          cache: true
          run-install: false
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/setup@v1
        with:
          version: 11.11.0
          install: false
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm check
      - run: pnpm run test
      - run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
